name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # This triggers the script every time you push to 'main'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        # We add 'force' to bypass the binding conflict and 'platform' to ensure Linux files are used
        run: |
          npm install --platform=linux --arch=x64 --force
          npm install @tailwindcss/oxide-linux-x64-musl --force

      - name: Build Project
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_PAYSTACK_PUBLIC_KEY: ${{ secrets.VITE_PAYSTACK_PUBLIC_KEY }}
